### ISSUE TITLE
Problem at finding necessary assets

### ISSUE THREAD

**Issue by prialgon** [Coolgolf1/Fisiks#1]
I've come across an error when running `main.py` from my Ubuntu WSL machine.
This error pops up:
```❯ python3 main.py
pygame 2.5.2 (SDL 2.28.2, Python 3.10.9)
Hello from the pygame community. https://www.pygame.org/contribute.html
Traceback (most recent call last):
  File "/home/prialgon/fisiks/Fisiks/main.py", line 10, in <module>
    quit_game, screen_size = f.choose_resolution_screen()
  File "/home/prialgon/fisiks/Fisiks/functions.py", line 1100, in choose_resolution_screen
    icon = pygame.image.load(".\\assets\\icon.png")
FileNotFoundError: No file '.\assets\icon.png' found in working directory '/home/prialgon/fisiks/Fisiks'.
```

After analyzing the file, I think it may be due to the fact that Linux & MacOS work with "/" when opening files and folders, while you use "\\" when defining the path. I suggest you modify this so that "Fisiks" works on multiple platforms. @Coolgolf1  please fix this issue ASAP.

**Comment by Coolgolf1** [comment]
Hey, prialgon!

Thanks for calling that error out, I did not think about it at all.

I have changed the code and it should now work on Windows, Linux, or any other OS. 

If you do find any other bugs please report them, thank you!! :)

**Comment by prialgon** [comment]
Great thanks!
